
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Emlak
{

using System;
    using System.Collections.Generic;
    
public partial class vwEvDetay
{

    public int emlakNumarasi { get; set; }

    public string evTuru { get; set; }

    public string evDurumu { get; set; }

    public int odaSayisi { get; set; }

    public int toplamEvAlani { get; set; }

    public System.DateTime yapimTarihi { get; set; }

    public string ilAdi { get; set; }

    public string ilceAdi { get; set; }

    public string semt { get; set; }

    public string evTipi { get; set; }

    public Nullable<int> satisFiyati { get; set; }

    public Nullable<int> kiraFiyati { get; set; }

    public Nullable<int> depozitoMiktari { get; set; }

}

}
